GET http://localhost/site


###

POST http://localhost/site
Content-Type: application/json

{
  "email": "fastrapier13@yandex.ru",
  "password": "qwerty13"
}

###
PUT http://localhost/site/4
Content-Type: application/json

{
  "email": "daniil.evgenyevich703@gmail.com",
  "password": "123"
}

###
DELETE http://localhost/site/2