GET http://localhost/users

###

POST http://localhost/users
Content-Type: application/json

{
  "email": "admin@admin.ru",
  "password": "admin"
}

###
PUT http://localhost/users/4
Content-Type: application/json

{
  "email": "daniil.evgenyevich703@gmail.com",
  "password": "123"
}

###
DELETE http://localhost/users/2